import Head from "next/head";
// Containers
import Hero from "../containers/home/Hero";
import Statistics from "../containers/home/Statistics";
import Features from "../containers/home/Features";
import Examples from "../containers/home/Examples";
import Start from "../containers/Start";

export default function Home() {
  return (
    <>
      <Head>
        <title>Prismane / Make great apps, ultra fast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Statistics />
      <Features />
      <Examples />
      <Start />
    </>
  );
}
