import Head from "next/head";
// Containers
import Hero from "@/containers/about-us/Hero";
import History from "@/containers/about-us/History";
import Future from "@/containers/about-us/Future";
import Values from "@/containers/about-us/Values";
import Contribute from "@/containers/about-us/Contribute";
import Start from "@/containers/Start";

export default function About_Us() {
  return (
    <>
      <Head>
        <title>Prismane / About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <History />
      <Future />
      <Values />
      <Contribute />
      <Start />
    </>
  );
}
